name: flutter_tabbar_lite
description: FlutterTabBarLite is a custom tab bar widget with animation, horizontal & vertical features.
version: 0.0.6
homepage: https://github.com/kh1amirhamza/flutter_tabbar_lite

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
